@startuml "Classes"

top to bottom direction

' Esta é uma classe:
class Alerta <<abstract>> {
  - number timerHandler
  + Date horario
  + boolean absoluto
  + string descricao
  + cancelar()
}
note left of Alerta : Alerta programado.\n\nPossui uma descrição que é\nexibida com a conclusão do\ntimer, na forma de um alerta.

' Novo comentário:
class AlertaRelativo {
  constructor(desc, horExpr)
  + ajustar(horExpr)
  + string: getTempoRestante()
}

class AlertaAbsoluto {
  + ajustar(horAbs)
  constructor(desc, horAbs)
}

Alerta <|-- AlertaRelativo
Alerta <|-- AlertaAbsoluto

class NoFim {
  - atributo
}

@enduml
